create table client(
                       id int generated by default as identity primary key,
                       full_name varchar(100) not null,
                       email varchar(150) not null unique,
                       passport_number int not null unique
);

create table credit_offer(
                             id int generated by default as identity primary key,
                             credit_limit decimal not null,
                             percent int not null
);

create table credit(
                       id int generated by default as identity primary key,
                       client_id int references client(id) on delete cascade,
                       credit_offer_id int references credit_offer(id),
                       amount decimal not null,
					   month_quantity int not null
);

create table payment(
                        id int generated by default as identity primary key,
                        date_of_payment date not null,
                        overall_amount decimal not null,
                        credit_body_amount decimal not null,
                        percent_amount decimal not null,
                        credit_id int references credit(id) on delete cascade
);

create table "current_user"(
                               id int generated by default as identity primary key,
                               username varchar not null unique,
                               password varchar not null
);